name: Run Scala Native tests on macOS - baselevel 2
on:
#  schedule:
#    - cron: '0 * * * *'

  workflow_dispatch:
  
jobs:
  macOS-bl2:
    name: macOs bl2
    runs-on: macos-10.15
## Read https://github.com/actions/virtual-environments/blob/main/images\
##     /macos/macos-10.15-Readme.md to see what software is stock in the soup.

    steps:
      - uses: actions/checkout@v2

      - name: macOS - bl2 prologue

        run: |
          echo "Hello World from maybe macOS"
          echo "$(uname -a)"

## 2021-03-12 17:24 -0500 llvm 11 already installed, 
## Looks like java 8 compiler is also installed.

## Someday may want to actively check these versions
#          which javac


      - name: macOS - Log active software versions
        run: |
          clang --version
          javac -version

## 2021-03-12 17:42 -0500 Goal - install java 8 & Sbt 1.4.9
## Use stock sbt launcher, not sbt-extras or such. Avoid schism.

## I hypothesize that neither Java nor Sbt is available ab ovo.

      - name: Setup Java and Sbt
        run: |
          brew install sbt
          sbt --version

# -30- #
