name: Run Scala Native tests on macOS - baselevel 2
on:
#  schedule:
#    - cron: '0 * * * *'

  workflow_dispatch:
  
jobs:
  macOS-bl2:
    name: macOs bl2
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: macOS - bl2 prologue

        run: |
          echo "Hello World from maybe macOS"
          echo "$(uname -a)"

## 2021-03-12 17:24 -0500 llvm 11 already installed, 

      - name: macOS - bl2 install software
        run: |
          clang --version
          

# -30- #
