name: Say "Hello World" every 15 minutes. 14

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

jobs:
  say-hello:
    name: Test say-hello
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: |
          echo "Hello World! $(date -Imin) 10"

# -30- #
