name: Send say "Hello World" every 5 minutes.

on:
  schedule:
  - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: |
          echo "Hello, world!"

# -30- #
