name: Say "Hello World" every 5 minutes. 6

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  say-hello:
    name: Test say-hello
    runs-on: Ubuntu-20.04
    steps:
      - name: Hello World
        run: |
          echo "Hello World! $(date -Imin)"

# -30- #
